inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-gitlab-security
  - rubocop-minitest
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - 'gemfiles/vendor/**/*'
    - 'vendor/bundle/**/*'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Lint/SuppressedException:
  Exclude:
    - 'spec/spec_helper.rb'

Minitest/EmptyLineBeforeAssertionMethods:
  Enabled: true